[workspace]
authors = ["Christopher Deutsch <hello@cdeutsch.org>"]
channels = ["conda-forge"]
name = "pynw"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]
build = "maturin develop --release"
test = { cmd = "pytest", depends-on = ["build"] }
lint = "lefthook run pre-commit --all-files --fail-on-changes"
check = "lefthook run pre-push --all-files"
docs = { cmd = "pdoc pynw --math --edit-url pynw=https://github.com/chrisdeutsch/pynw/blob/main/pynw/ -o site", depends-on = [
  "build",
] }
docs-serve = { cmd = "pdoc pynw --math --edit-url pynw=https://github.com/chrisdeutsch/pynw/blob/main/pynw/", depends-on = [
  "build",
] }

[dependencies]
python = ">=3.10"
numpy = ">=1.22"

[feature.build.dependencies]
pip = "*"
rust = "*"
rust-src = "*"
maturin = "*"

[feature.test.dependencies]
pytest = "*"
pytest-benchmark = "*"
hypothesis = "*"
rapidfuzz = "*"
scipy = "*"
inline-snapshot = "*"

[feature.mypy.dependencies]
mypy = "*"

[feature.lint.dependencies]
ruff = "*"
markdownlint-cli = "*"
prettier = "*"
actionlint = "*"
lefthook = "*"
taplo = "*"

[feature.docs.dependencies]
pdoc = "*"

[feature.py310.dependencies]
python = "3.10.*"

[feature.py314.dependencies]
python = "3.14.*"

[feature.numpy-oldest.dependencies]
numpy = "1.22.*"

[feature.numpy-latest.dependencies]
numpy = "2.4.*"

[environments]
default = ["build", "test", "mypy", "lint", "docs"]
py314-numpy-latest = ["py314", "numpy-latest", "build", "test", "mypy"]
py310-numpy-oldest = ["py310", "numpy-oldest", "build", "test", "mypy"]
